import type { Metadata } from "next";
import "@/node_modules/react-modal-video/css/modal-video.css";
import "../public/assets/css/style.css";
import "swiper/css";
// import "swiper/css/navigation"
import "swiper/css/pagination";
import "swiper/css/free-mode";
import { dM_Sans } from "@/lib/font";

export const metadata: Metadata = {
  title: "Immo App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${dM_Sans.variable}`}
      data-scroll-behavior="smooth"
    >
      <body suppressHydrationWarning={true} >{children}</body>
    </html>
  );
}
